spring:
  mvc:
    view:
      suffix: .html

  profiles:
    active: dev
    include: personal

  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
  #    timeout: 30m # 세션 생성 후 30분 동안 유효, 이후에 자동 만료

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver

server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

  devtools:
    restart:
      enabled: false

logging:
  level:
    org:
      hibernate.SQL: debug
      springframework:
        core.LocalVariableTableParameterNameDiscoverer: ERROR


thymeleaf:
  prefix=classpath: templates/
  suffix: .html
  check-template-location: true
  cache: false
  mvc:
    static-path-pattern: "/static/**"