spring:
  mvc:
    view:
      suffix: .html

  profiles:
    active: dev
    include: personal

  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
  #    timeout: 30m # 세션 생성 후 30분 동안 유효, 이후에 자동 만료

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver

server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

  devtools:
    restart:
      enabled: true

logging:
  level:
    org:
      hibernate.SQL: debug
      springframework:
        core.LocalVariableTableParameterNameDiscoverer: ERROR

management:
  info:
    java:
      enabled: true
    os:
      enabled: true
    env:
      enabled: true
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
  server:
    port: 8080
  tomcat:
    mbeanregistry:
      enabled: true

thymeleaf:
  prefix=classpath: templates/
  suffix: .html
  check-template-location: true
  cache: false
  mvc:
    static-path-pattern: "/static/**"

---
spring:
  datasource:
    url: jdbc:mysql://backend-roadmap.ciewy1yktvwv.ap-northeast-2.rds.amazonaws.com:3306/backend_roadmap
    username: admin
    password: admin1234
    driver-class-name: com.mysql.jdbc.Driver

  config:
    activate:
      on-profile: prod
      include: personal

  session:
    store-type: jdbc
    jdbc:
      initialize-schema: embedded

  jpa:
    database: mysql
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        format_sql: true
        use_sql_comments: true

server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

  devtools:
    restart:
      enabled: true

data:
  web:
    pageable:
      default-page-size: 10 #기본 page 사이즈(Web 확장)
      max-page-size: 2000 #최대 page 사이즈(Web 확장)

logging:
  level:
    org:
      hibernate.SQL: debug

management:
  info:
    java:
      enabled: true
    os:
      enabled: true
    env:
      enabled: true
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
  server:
    port: 8080
  tomcat:
    mbeanregistry:
      enabled: true

thymeleaf:
  prefix=classpath: templates/
  suffix: .html
  check-template-location: true
  cache: false
  mvc:
    static-path-pattern: "/static/**"